const DATA={
profile:{name:'Mosab Mohamed Osman',target:'Customer Service / Customer Care / Call Center / Support',location:'Riyadh, Saudi Arabia',source:'CV + verified LinkedIn profile'},
opportunities:[
{id:1,company:'Veeam Software',role:'IT Support Specialist II',location:'Riyadh',date:'2026-08-13',source:'Official career page',url:'https://job-boards.eu.greenhouse.io/veeamsoftware/jobs/4878223101',status:'فرصة للمتابعة',type:'IT Support',experience:'2+ years',notes:'Service Desk / Desktop Support; Windows; AD; Microsoft 365. لم يتم تسجيل إرسال مؤكد في السجل الحالي.'},
{id:2,company:'eSense',role:'Support Engineer',location:'Riyadh',date:'2026-08-13',source:'Official career page',url:'https://new.esensesoftware.com/l1-support-engineer/',status:'فرصة للمتابعة',type:'Support',experience:'غير محدد',notes:'دعم فني للعملاء واستكشاف الأعطال ونظام التذاكر. لم يتم تسجيل إرسال مؤكد.'},
{id:3,company:'Motorola Solutions',role:'Customer Support Engineer',location:'Riyadh',date:'2026-08-13',source:'Official career page',url:'https://motorolasolutions.wd5.myworkdayjobs.com/en-US/Careers/job/Customer-Support-Engineer_R64657',status:'فرصة للمتابعة',type:'Customer Support',experience:'حسب الإعلان',notes:'دعم العملاء وتحليل المشكلات والتنسيق مع الفرق الهندسية. لم يتم تسجيل إرسال مؤكد.'},
{id:4,company:'ANMAT',role:'Technical Support Engineer',location:'Riyadh',date:'2026-08-11',source:'Previously reviewed',url:'',status:'غير مؤكد',type:'Technical Support',experience:'غير محدد',notes:'ظهر سابقًا ضمن البحث؛ لا يوجد في السجل الحالي دليل مؤكد على إرسال الطلب أو الرد.'},
{id:5,company:'Fircroft',role:'L1 Deskside / IT Support',location:'Riyadh',date:'2026-08-11',source:'Previously reviewed',url:'',status:'غير مؤكد',type:'IT Support',experience:'غير محدد',notes:'ظهر سابقًا ضمن البحث؛ لا يوجد في السجل الحالي دليل مؤكد على إرسال الطلب أو الرد.'}
],
applications:[],communications:[],
searches:[{date:'2026-08-14',count:3,query:'Customer Service / Customer Care / Call Center / Support',location:'Saudi Arabia / Riyadh'},{date:'2026-08-13',count:3,query:'Customer Service / Support',location:'Riyadh'},{date:'2026-08-11',count:5,query:'Customer Service / Technical Support',location:'Riyadh'}]
};
const state={view:'overview',q:'',status:'all',company:'all',type:'all',page:1,perPage:10};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function tag(s){let c=s.includes('مؤكد')&&!s.includes('غير')?'ok':s.includes('فرصة')?'info':s.includes('غير')?'warn':'';return `<span class="tag ${c}">${esc(s)}</span>`}
function k(label,value,meta,cls){return `<div class="card kpi ${cls}"><div class="label">${label}</div><div class="value">${value}</div><div class="meta">${meta}</div></div>`}
function setView(v){state.view=v;state.page=1;const titles={overview:['نظرة عامة','ملخص كامل لحالة البحث والتقديم'],opportunities:['الفرص','كل الوظائف التي تم العثور عليها مع تفاصيلها'],applications:['الطلبات','الطلبات المؤكدة فقط، مع حالة كل طلب'],companies:['الشركات','الشركات والفرص المرتبطة بكل شركة'],communications:['الإيميلات والردود','سجل التواصل والردود المؤكدة'],analytics:['التحليلات','اتجاه البحث، معدلات التحويل، وتوزيع الحالات'],data:['البيانات','إدارة البيانات المحلية: تصدير، استيراد، وتوضيح مصدر الأرقام']};$('#viewTitle').textContent=titles[v][0];$('#viewSub').textContent=titles[v][1];$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}
function overview(){const o=DATA.opportunities,a=DATA.applications,c=[...new Set(o.map(x=>x.company))].length;const replies=DATA.communications.filter(x=>x.kind==='reply').length;return `<div class="grid kpis">${k('الفرص المكتشفة',o.length,'سجل الفرص الحالي','blue')}${k('الطلبات المؤكدة',a.length,'لم يتم تسجيل طلب جديد مؤكد','green')}${k('الشركات',c,'مرتبطة بالفرص المسجلة','purple')}${k('إيميلات مرسلة مؤكدة',DATA.communications.filter(x=>x.kind==='sent').length,'لا يوجد إرسال مؤكد في السجل','orange')}${k('الردود المؤكدة',replies,'من Gmail/سجل التواصل','cyan')}${k('العروض الوظيفية',a.filter(x=>x.status==='عرض وظيفي').length,'المؤكد فقط','red')}</div><div class="grid two section"><div class="card"><div class="section-head"><h2>حالة السجل الآن</h2>${tag('بيانات مؤكدة')}</div><div class="notice">تم الفصل بين <b>الفرص التي عُثر عليها</b> وبين <b>الطلبات التي تم إرسالها فعليًا</b>. لا يتم احتساب فرصة على أنها طلب، ولا يتم احتساب رد أو قبول بدون سجل مؤكد.</div><div class="bars" style="margin-top:15px">${[['فرص للمتابعة',o.filter(x=>x.status==='فرصة للمتابعة').length],['غير مؤكد',o.filter(x=>x.status==='غير مؤكد').length],['طلبات مؤكدة',a.length],['ردود مؤكدة',replies]].map(([n,v])=>`<div class="barrow"><span>${n}</span><div class="bar"><i style="width:${Math.min(100,v?Math.max(8,v/o.length*100):0)}%"></i></div><b>${v}</b></div>`).join('')}</div></div><div class="card"><div class="section-head"><h2>الملف المستهدف</h2></div><div class="profile"><div class="avatar">M</div><div><b>${esc(DATA.profile.name)}</b><p style="margin:2px 0;color:#71809a;font-size:11px">${esc(DATA.profile.target)}</p><small>${esc(DATA.profile.location)}</small></div></div><div class="detail-grid" style="margin-top:15px"><div class="detail"><small>مصدر البيانات</small><b>CV + LinkedIn</b></div><div class="detail"><small>آخر تحديث</small><b>14 أغسطس 2026</b></div></div></div></div><div class="grid two section"><div class="card"><div class="section-head"><h2>الفرص الأخيرة</h2><button class="smallbtn" onclick="setView('opportunities')">عرض الكل</button></div>${recentTable(o.slice(0,5))}</div><div class="card"><div class="section-head"><h2>نشاط البحث</h2></div><div class="chart">${DATA.searches.map(x=>{let h=Math.max(8,x.count*35);return `<div class="col"><div class="fill" style="height:${h}px"></div><b>${x.count}</b><small>${x.date.slice(5)}</small></div>`}).join('')}</div></div></div>`}
function recentTable(rows){if(!rows.length)return '<div class="empty">لا توجد سجلات</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>الشركة</th><th>الوظيفة</th><th>الموقع</th><th>التاريخ</th><th>الحالة</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.company)}</b></td><td>${esc(x.role)}<div style="color:#8a96a7;font-size:10px">${esc(x.type)}</div></td><td>${esc(x.location)}</td><td>${esc(x.date)}</td><td>${tag(x.status)}</td><td><button class="smallbtn" onclick="showOpp(${x.id})">تفاصيل</button></td></tr>`).join('')}</tbody></table></div>`}
function opportunities(){let rows=filteredOpp();let pages=Math.max(1,Math.ceil(rows.length/state.perPage));state.page=Math.min(state.page,pages);let slice=rows.slice((state.page-1)*state.perPage,state.page*state.perPage);return `<div class="card"><div class="toolbar"><input id="q" value="${esc(state.q)}" placeholder="بحث باسم الشركة أو الوظيفة..."><select id="status"><option value="all">كل الحالات</option><option>فرصة للمتابعة</option><option>غير مؤكد</option></select><select id="type"><option value="all">كل الأنواع</option>${[...new Set(DATA.opportunities.map(x=>x.type))].map(t=>`<option>${esc(t)}</option>`).join('')}</select><button class="btn" id="clear">مسح الفلاتر</button></div>${recentTable(slice)}<div class="pagination">${Array.from({length:pages},(_,i)=>`<button onclick="goPage(${i+1})" style="font-weight:${state.page===i+1?'800':'400'}">${i+1}</button>`).join('')}</div><div class="footer-note">إجمالي النتائج بعد الفلترة: ${rows.length}</div></div>`}
function filteredOpp(){let q=state.q.toLowerCase();return DATA.opportunities.filter(x=>(!q||`${x.company} ${x.role} ${x.type} ${x.notes}`.toLowerCase().includes(q))&&(state.status==='all'||x.status===state.status)&&(state.type==='all'||x.type===state.type))}
function applications(){return `<div class="card"><div class="section-head"><h2>الطلبات المؤكدة</h2>${tag(DATA.applications.length?'سجل موثق':'لا توجد طلبات مؤكدة')}</div>${DATA.applications.length?recentTable(DATA.applications):'<div class="empty">لا يوجد في البيانات الحالية أي طلب تم تأكيد إرساله فعليًا. سيتم وضع الطلب هنا فقط بعد تسجيل الإرسال.</div>'}</div><div class="card section"><div class="section-head"><h2>ما لا يتم احتسابه تلقائيًا</h2></div><div class="notice">الإعلانات التي تم العثور عليها لا تُحسب كطلبات. كذلك لا تُحسب الرسائل أو الردود أو القبول إلا إذا كان هناك سجل موثوق لها.</div></div>`}
function companies(){let map={};DATA.opportunities.forEach(o=>(map[o.company]??=[]).push(o));return `<div class="grid three">${Object.entries(map).map(([c,rows])=>`<div class="card"><div class="split"><h3 style="margin:0;font-size:15px">${esc(c)}</h3>${tag(`${rows.length} فرصة`)}</div><div class="list" style="margin-top:10px">${rows.map(r=>`<div class="list-item"><b>${esc(r.role)}</b><p>${esc(r.location)} · ${esc(r.date)}</p><div>${tag(r.status)}</div></div>`).join('')}</div></div>`).join('')}</div>`}
function communications(){return `<div class="grid two"><div class="card"><div class="section-head"><h2>الإيميلات المرسلة</h2>${tag('مؤكد فقط')}</div>${DATA.communications.filter(x=>x.kind==='sent').length?recentComms('sent'):'<div class="empty">لا يوجد إرسال مؤكد مسجل حاليًا.</div>'}</div><div class="card"><div class="section-head"><h2>الردود</h2>${tag('مؤكد فقط')}</div>${DATA.communications.filter(x=>x.kind==='reply').length?recentComms('reply'):'<div class="empty">لا توجد ردود مؤكدة مسجلة حاليًا.</div>'}</div></div>`}
function recentComms(kind){return `<div class="list">${DATA.communications.filter(x=>x.kind===kind).map(x=>`<div class="list-item"><b>${esc(x.subject)}</b><p>${esc(x.from||x.to||'')} · ${esc(x.date)}</p><p>${esc(x.body||'')}</p></div>`).join('')}</div>`}
function analytics(){const total=DATA.opportunities.length,follow=DATA.opportunities.filter(x=>x.status==='فرصة للمتابعة').length;return `<div class="grid three">${k('إجمالي الفرص',total,'كل المصادر المسجلة','blue')}${k('نسبة الفرص القابلة للمتابعة',total?Math.round(follow/total*100)+'%':'0%','ليست نسبة قبول وظيفي','green')}${k('نسبة التحويل المؤكدة',DATA.applications.length?Math.round(DATA.applications.length/total*100)+'%':'0%','طلبات / فرص','purple')}</div><div class="grid two section"><div class="card"><div class="section-head"><h2>عدد الفرص حسب اليوم</h2></div><div class="chart">${DATA.searches.map(x=>{let h=Math.max(10,x.count*35);return `<div class="col"><div class="fill" style="height:${h}px"></div><b>${x.count}</b><small>${x.date}</small></div>`}).join('')}</div></div><div class="card"><div class="section-head"><h2>توزيع نوع الوظائف</h2></div><div class="bars">${Object.entries(DATA.opportunities.reduce((m,x)=>(m[x.type]=(m[x.type]||0)+1,m),{})).map(([n,v])=>`<div class="barrow"><span>${esc(n)}</span><div class="bar"><i style="width:${v/total*100}%"></i></div><b>${v}</b></div>`).join('')}</div></div></div><div class="card section"><h2 style="font-size:15px">ملاحظة منهجية</h2><p style="font-size:11px;color:#71809a;line-height:1.9">هذه التحليلات لا تستخدم أرقامًا تقديرية للطلبات أو الردود. إذا لم يوجد سجل مؤكد، يظهر الرقم صفر حتى يتم إدخال/استلام دليل جديد.</p></div>`}
function dataView(){return `<div class="grid two"><div class="card"><h2 style="font-size:16px">مصادر البيانات</h2><div class="detail-grid"><div class="detail"><small>الملف الشخصي</small><b>CV + LinkedIn</b></div><div class="detail"><small>مصدر الفرص</small><b>سجل البحث الحالي</b></div><div class="detail"><small>الطلبات</small><b>السجل المؤكد فقط</b></div><div class="detail"><small>الإيميلات</small><b>السجل المؤكد فقط</b></div></div><div class="notice" style="margin-top:12px">الموقع ثابت على GitHub Pages. البيانات المحلية يمكن تصديرها واستيرادها، لكن الربط المباشر مع Gmail/LinkedIn يحتاج قناة اتصال مصرح بها؛ لذلك لن يعرض الموقع بيانات غير مؤكدة.</div></div><div class="card"><h2 style="font-size:16px">إدارة البيانات</h2><div class="actions"><button class="btn" id="export">تصدير JSON</button><label class="btn" for="importFile">استيراد JSON</label><input id="importFile" type="file" accept="application/json" hidden><button class="danger-btn" id="reset">إعادة البيانات الأصلية</button></div><p class="footer-note">التصدير يحفظ جميع البيانات الموجودة حاليًا في المتصفح.</p></div></div><div class="card section"><h2 style="font-size:16px">كل الفرص بالتفصيل</h2>${recentTable(DATA.opportunities)}</div>`}
function showOpp(id){let x=DATA.opportunities.find(a=>a.id===id);if(!x)return;$('#modalBody').innerHTML=`<h2>${esc(x.role)}</h2><div class="detail-grid"><div class="detail"><small>الشركة</small><b>${esc(x.company)}</b></div><div class="detail"><small>الموقع</small><b>${esc(x.location)}</b></div><div class="detail"><small>التاريخ</small><b>${esc(x.date)}</b></div><div class="detail"><small>المصدر</small><b>${esc(x.source)}</b></div><div class="detail"><small>الخبرة</small><b>${esc(x.experience)}</b></div><div class="detail"><small>الحالة</small><b>${tag(x.status)}</b></div></div><div class="notice" style="margin-top:14px">${esc(x.notes)}</div><div class="actions" style="margin-top:14px">${x.url?`<a class="btn" href="${esc(x.url)}" target="_blank" rel="noopener">فتح إعلان الوظيفة</a>`:''}<button class="btn" onclick="closeModal()">إغلاق</button></div>`;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function goPage(p){state.page=p;render()}
function bind(){const q=$('#q');if(q){q.oninput=e=>{state.q=e.target.value;state.page=1;render()};$('#status').value=state.status;$('#type').value=state.type;$('#status').onchange=e=>{state.status=e.target.value;state.page=1;render()};$('#type').onchange=e=>{state.type=e.target.value;state.page=1;render()};$('#clear').onclick=()=>{state.q='';state.status='all';state.type='all';render()}}$('#export')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(DATA,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mosab-job-dashboard-data.json';a.click()});$('#importFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{Object.assign(DATA,JSON.parse(r.result));render();alert('تم استيراد البيانات بنجاح')}catch{alert('ملف JSON غير صالح')}};r.readAsText(f)});$('#reset')?.addEventListener('click',()=>{location.reload()})}
function render(){let html=state.view==='overview'?overview():state.view==='opportunities'?opportunities():state.view==='applications'?applications():state.view==='companies'?companies():state.view==='communications'?communications():state.view==='analytics'?analytics():dataView();$('#content').innerHTML=html;bind()}
$$('#nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#refresh').onclick=()=>{const b=$('#refresh');b.textContent='✓ تم التحديث';setTimeout(()=>b.textContent='↻ تحديث',1200);render()};$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});window.showOpp=showOpp;window.closeModal=closeModal;window.goPage=goPage;window.setView=setView;render();setInterval(()=>{const el=document.querySelector('.eyebrow');if(el)el.textContent=new Intl.DateTimeFormat('ar-SA',{dateStyle:'full'}).format(new Date())},60000);